### ISSUE TITLE
Individual min/max values for gauges

### ISSUE THREAD

**Issue by Rocka84** [Rocka84/dual-gauge-card#1]
It should be possible to define max and min values for both gauges at once (as is) or for each gauge individualy.

**Comment by VirtualL** [comment]
I was making it worked, please get my pull request

**Comment by Rocka84** [comment]
Review of your pull request is already in progress, I wrote some comments for you. Lets discuss your solution over there.

Btw: please add "fixes #1" somewhere in your commit messages to automatically close this issue on merge.
