### ISSUE TITLE
Strange gauge when values outside min/max

### ISSUE THREAD

**Issue by optama** [Rocka84/dual-gauge-card#11]
When entity value is outside the range of min/max the gauge is shown as in attached image
![2019-05-27_00-21](https://user-images.githubusercontent.com/509056/58387800-73fade00-8015-11e9-9547-8c9c7d6f0505.png)

Expected:
- when value is < min: empty gauge
- when value is > max: full gauge

Not sure if this is a bug or as intended but I'd for instance like a general min max in temperature of 18-25 but some odd days the temperature might actually be outside this range and when that happens it looks weird if the gauge suddenly behaves strange.

The standard gauge shipped with home assistant works as expected.

**Comment by optama** [comment]
Created pr with customized code from official gauge.

**Comment by Rocka84** [comment]
fixed by pull request #12 by optama
Thx!
