### ISSUE TITLE
change Background-color of gauge

### ISSUE THREAD

**Issue by simonblau** [Rocka84/dual-gauge-card#9]
Hey,
it's not really an issue, but how can i change the background color of the gauge? Actually it's white when i have a dark card background and light grey when i have a white card background. Is there a way to adapt it inside the config or inside the themes? Like the gauge background of the "original" gauge card?

Greets and many thanks for this awesome dual gauge from Germany,
Simon

**Comment by Rocka84** [comment]
Hi,
sorry for the late answer.
Unfortunatly the background-color of the gauge is fixed at #e5e5e5 at the moment, I must have overlooked that earlier.
I plan to fix this by using theme-variables and an optional config override. As a workaround you could use some css to overwrite the color, e.g. `.gauge-background .circle { border-color: red }`.

**Comment by Rocka84** [comment]
Btw: Gern geschehen ;-)

Rocka84
